
before_build:
  - ps: .\Init.ps1

build_script:
  - ps: |
      Invoke-Build -Task ZipRelease -Configuration Release
      platyPS\Get-HelpPreview .\bin\Release\PSReadline\en-US\PSReadline.dll-help.xml > .\bin\Release\PSReadline.txt

artifacts:
  - path: .\bin\Release\PSReadline.zip
  - path: .\bin\Release\PSReadline.txt
